name: Mi Primer Robot ðŸ¤–

# El "Gatillo": Â¿CuÃ¡ndo se despierta el robot?
# Se activarÃ¡ cada vez que hagas un 'push' al repo.
on: [push]

jobs:
  tarea-de-prueba:
    # El "Entorno": Â¿DÃ³nde corre esto?
    # GitHub nos presta un servidor Linux (Ubuntu) gratis.
    runs-on: ubuntu-latest
    
    steps:
      - name: Paso 1 - Saludar al universo
        run: echo "Â¡Hola Mundo! Soy tu robot ejecutÃ¡ndose en la nube de GitHub."
      
      - name: Paso 2 - Mostrar fecha y hora del servidor
        run: date

      - name: Paso 3 - Listar archivos del sistema
        run: ls -la