name: Mi Primer Robot ü§ñ

on: [push]

jobs:
  saludo-cyberpunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4
      
      - name: Saludar al creador
        run: |
          echo "Iniciando sistemas..."
          echo "Hola Fernando. Soy tu asistente automatizado."
          echo "Todo parece estar en orden en el a√±o 2025."